"""
Evidence Schema — The universal data format for all OSINT intelligence.

Every piece of data collected, analyzed, or generated by the system flows through
this schema. It is the single source of truth for the intelligence pipeline.

Design principles:
- Source-agnostic: works for Reddit, web search, breach data, WHOIS, etc.
- Entity-first: extracted entities are first-class citizens
- Traceable: every item links back to its origin
- Extensible: metadata dict absorbs source-specific fields
"""

import uuid
from enum import Enum
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any


# ─── Enums ────────────────────────────────────────────────────────────────────

class SourceType(str, Enum):
    """All supported evidence source types."""
    REDDIT_POST = "reddit_post"
    REDDIT_COMMENT = "reddit_comment"
    REDDIT_USER = "reddit_user"
    WEB_SEARCH = "web_search"
    BREACH_DATA = "breach_data"
    USERNAME_DISCOVERY = "username_discovery"
    DOMAIN_INTEL = "domain_intel"
    IMAGE_ANALYSIS = "image_analysis"
    CODE_SEARCH = "code_search"
    MANUAL = "manual"


class EntityType(str, Enum):
    """All entity types that can be extracted from evidence."""
    PERSON = "person"
    EMAIL = "email"
    USERNAME = "username"
    URL = "url"
    PHONE = "phone"
    ORGANIZATION = "organization"
    LOCATION = "location"
    IP_ADDRESS = "ip_address"
    DOMAIN = "domain"
    DATE = "date"
    HASHTAG = "hashtag"
    SUBREDDIT = "subreddit"
    CRYPTO_WALLET = "crypto_wallet"


class EvidenceStatus(str, Enum):
    """Processing lifecycle status."""
    RAW = "raw"
    PROCESSED = "processed"
    VALIDATED = "validated"
    ARCHIVED = "archived"


# ─── Data Classes ─────────────────────────────────────────────────────────────

@dataclass
class EntityRecord:
    """A single extracted entity from evidence content."""
    type: str           # EntityType value
    value: str          # The actual entity text
    confidence: float   # 0.0 to 1.0
    source: str = ""    # Extraction method: "ner", "regex", "manual"
    context: str = ""   # Surrounding text for context

    def to_dict(self) -> Dict[str, Any]:
        return {
            "type": self.type,
            "value": self.value,
            "confidence": round(self.confidence, 3),
            "source": self.source,
            "context": self.context
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "EntityRecord":
        return cls(
            type=data.get("type", ""),
            value=data.get("value", ""),
            confidence=data.get("confidence", 0.0),
            source=data.get("source", ""),
            context=data.get("context", "")
        )


@dataclass
class EvidenceContent:
    """Flexible content block — adapts to any source type."""
    title: str = ""
    body: str = ""
    url: str = ""
    raw: Optional[Dict[str, Any]] = None  # Preserve original data

    def to_dict(self) -> Dict[str, Any]:
        result = {
            "title": self.title,
            "body": self.body,
            "url": self.url,
        }
        if self.raw is not None:
            result["raw"] = self.raw
        return result

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "EvidenceContent":
        return cls(
            title=data.get("title", ""),
            body=data.get("body", ""),
            url=data.get("url", ""),
            raw=data.get("raw")
        )


@dataclass
class EvidenceTimestamps:
    """Temporal tracking for evidence lifecycle."""
    source_created: Optional[str] = None   # When the original content was created
    collected_at: str = ""                  # When we collected it
    processed_at: Optional[str] = None      # When entity extraction ran

    def to_dict(self) -> Dict[str, Any]:
        return {
            "source_created": self.source_created,
            "collected_at": self.collected_at,
            "processed_at": self.processed_at
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "EvidenceTimestamps":
        return cls(
            source_created=data.get("source_created"),
            collected_at=data.get("collected_at", ""),
            processed_at=data.get("processed_at")
        )


@dataclass
class EvidenceItem:
    """
    The universal evidence record — the atomic unit of all OSINT intelligence.
    
    Every connector, extractor, and analyzer produces or consumes these.
    """
    evidence_id: str
    source_type: str            # SourceType value
    source_id: str              # Original ID from source system
    source_platform: str        # Platform name (reddit, duckduckgo, etc.)
    content: EvidenceContent
    entities: List[EntityRecord]
    metadata: Dict[str, Any]    # Source-specific metadata (flexible)
    timestamps: EvidenceTimestamps
    confidence: float           # 0.0 to 1.0 — overall reliability
    tags: List[str]
    investigation_id: Optional[str] = None
    status: str = EvidenceStatus.RAW.value

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to MongoDB-compatible dict."""
        return {
            "evidence_id": self.evidence_id,
            "source_type": self.source_type,
            "source_id": self.source_id,
            "source_platform": self.source_platform,
            "content": self.content.to_dict(),
            "entities": [e.to_dict() for e in self.entities],
            "metadata": self.metadata,
            "timestamps": self.timestamps.to_dict(),
            "confidence": round(self.confidence, 3),
            "tags": self.tags,
            "investigation_id": self.investigation_id,
            "status": self.status
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "EvidenceItem":
        """Deserialize from MongoDB document."""
        return cls(
            evidence_id=data.get("evidence_id", ""),
            source_type=data.get("source_type", ""),
            source_id=data.get("source_id", ""),
            source_platform=data.get("source_platform", ""),
            content=EvidenceContent.from_dict(data.get("content", {})),
            entities=[EntityRecord.from_dict(e) for e in data.get("entities", [])],
            metadata=data.get("metadata", {}),
            timestamps=EvidenceTimestamps.from_dict(data.get("timestamps", {})),
            confidence=data.get("confidence", 0.0),
            tags=data.get("tags", []),
            investigation_id=data.get("investigation_id"),
            status=data.get("status", EvidenceStatus.RAW.value)
        )

    def get_text_content(self) -> str:
        """Return combined text content for NLP processing."""
        parts = []
        if self.content.title:
            parts.append(self.content.title)
        if self.content.body:
            parts.append(self.content.body)
        return " ".join(parts)

    def get_entities_by_type(self, entity_type: str) -> List[EntityRecord]:
        """Filter entities by type."""
        return [e for e in self.entities if e.type == entity_type]

    def has_entity(self, entity_type: str, value: str) -> bool:
        """Check if a specific entity exists."""
        normalized = value.lower().strip()
        return any(
            e.type == entity_type and e.value.lower().strip() == normalized
            for e in self.entities
        )


# ─── Validation ───────────────────────────────────────────────────────────────

def validate_evidence_item(item: EvidenceItem) -> tuple:
    """
    Validate an evidence item before storage.
    Returns (is_valid: bool, errors: list[str])
    """
    errors = []

    if not item.evidence_id:
        errors.append("evidence_id is required")

    if not item.source_type:
        errors.append("source_type is required")
    elif item.source_type not in [st.value for st in SourceType]:
        errors.append(f"Invalid source_type: {item.source_type}")

    if not item.source_id:
        errors.append("source_id is required")

    if not item.source_platform:
        errors.append("source_platform is required")

    if item.confidence < 0.0 or item.confidence > 1.0:
        errors.append(f"confidence must be 0.0-1.0, got {item.confidence}")

    if item.status not in [s.value for s in EvidenceStatus]:
        errors.append(f"Invalid status: {item.status}")

    # Validate entities
    valid_entity_types = [et.value for et in EntityType]
    for i, entity in enumerate(item.entities):
        if entity.type not in valid_entity_types:
            errors.append(f"Entity[{i}] has invalid type: {entity.type}")
        if not entity.value:
            errors.append(f"Entity[{i}] has empty value")
        if entity.confidence < 0.0 or entity.confidence > 1.0:
            errors.append(f"Entity[{i}] confidence out of range: {entity.confidence}")

    return (len(errors) == 0, errors)


def generate_evidence_id() -> str:
    """Generate a unique evidence ID."""
    return f"evi_{uuid.uuid4().hex[:16]}"
